version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: db_sistema
    restart: always
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres  
      POSTGRES_DB: banco_dsd     
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

  core-soap:
    build: ./BancoCoreSOAP
    container_name: container_soap
    depends_on:
      - db
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/banco_dsd
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SERVER_PORT=8081
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    ports:
      - "8081:8081" 
    networks:
      - app-network

  rest-api:
    build: ./BancoRestApi
    container_name: container_rest
    depends_on:
      - db
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/banco_dsd
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SERVER_PORT=8081
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    ports:
      - "8082:8081"
    networks:
      - app-network

  ws-service:
    build: ./ws-service
    container_name: container_ws
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
      - RABBITMQ_URL=amqp://rabbitmq:5672 
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: projeto-dsd-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"      # AMQP
      - "15672:15672"    # Management UI
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  atm-monitor:
    build: ./ATMService
    container_name: atm-monitor
    command: npx ts-node monitor-server.ts
    ports:
      - "6000:6000/udp" # UDP (Status Heartbeat)
      - "6001:6001"     # TCP (ATM Comandos)
      - "6002:6002"     # TCP (Gateway Interface)
    networks:
      - app-network
    restart: always

  atm-cluster:
    build: ./ATMService
    container_name: atm-cluster
    command: npx ts-node atm-cluster.ts
    environment:
      - MONITOR_HOST=atm-monitor 
    depends_on:
      - atm-monitor
    networks:
      - app-network
    restart: on-failure

  gateway:
    build: ./BancoApiGateway
    container_name: container_gateway
    depends_on:
      - core-soap
      - rest-api
      - ws-service
      - rabbitmq
      - atm-monitor 
    ports:
      - "8000:3000" 
    environment:
      - SOAP_URL=http://core-soap:8081
      - REST_URL=http://rest-api:8081
      - WS_URL=ws://ws-service:3000
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - PORT=3000
      - MONITOR_HOST=atm-monitor
    networks:
      - app-network

volumes:
  pg_data:

networks:
  app-network:
    driver: bridge