version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: db_sistema
    restart: always
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres  
      POSTGRES_DB: banco_dsd     
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

  core-soap:
    build: ./BancoCoreSOAP
    container_name: container_soap
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/banco_dsd
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SERVER_PORT=8081
    ports:
      - "8081:8081" 
    networks:
      - app-network

  rest-api:
    build: ./BancoRestApi
    container_name: container_rest
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/banco_dsd
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SERVER_PORT=8081
    ports:
      - "8082:8081"
    networks:
      - app-network

  ws-service:
    build: ./ws-service
    container_name: container_ws
    ports:
      - "8083:3000"
    networks:
      - app-network

  gateway:
    build: ./BancoApiGateway
    container_name: container_gateway
    depends_on:
      - core-soap
      - rest-api
      - ws-service
    ports:
      - "8000:3000" 
    environment:
      - SOAP_URL=http://core-soap:8081
      - REST_URL=http://rest-api:8081
      - WS_URL=ws://ws-service:3000
      - PORT=3000
    networks:
      - app-network

volumes:
  pg_data:

networks:
  app-network:
    driver: bridge